name: Merge Text Files
'on':
  push:
    branches:
      - main
jobs:
  merge-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Merge text files
        run: |
          cat 1.txt 2.txt > result.txt
      - name: Display result
        run: |
          echo "Merged content:"
          cat result.txt
